import { createClient, SupabaseClient } from '@supabase/supabase-js';

const env: Record<string, string | undefined> = (typeof import.meta !== 'undefined' && import.meta && (import.meta as any).env)
  ? (import.meta as any).env
  : (typeof process !== 'undefined' && process && process.env ? process.env : {});

const supabaseUrl = env?.VITE_SUPABASE_URL || '';
const supabaseAnonKey = env?.VITE_SUPABASE_ANON_KEY || '';

export const isSupabaseConfigured = Boolean(
  supabaseUrl &&
  supabaseAnonKey &&
  supabaseUrl !== 'https://placeholder.supabase.co'
);

export const supabase: SupabaseClient = createClient(
  supabaseUrl || 'https://placeholder.supabase.co',
  supabaseAnonKey || 'placeholder-key'
);

/**
 * Uploads a base64 photo to Supabase Storage bucket "foto_temuan".
 * Returns fully qualified valid Supabase Public CDN URL.
 */
export async function uploadPhotoToSupabaseBucket(dataUrl: string): Promise<string> {
  if (!isSupabaseConfigured || !dataUrl || !dataUrl.startsWith('data:image/')) {
    return dataUrl;
  }

  try {
    const match = dataUrl.match(/^data:(image\/[a-zA-Z0-9\+\-]+);base64,(.+)$/);
    if (!match) return dataUrl;

    const contentType = match[1];
    const base64Data = match[2];

    const binaryStr = atob(base64Data);
    const bytes = new Uint8Array(binaryStr.length);
    for (let i = 0; i < binaryStr.length; i++) {
      bytes[i] = binaryStr.charCodeAt(i);
    }

    const fileExt = contentType.includes('png') ? 'png' : contentType.includes('webp') ? 'webp' : 'jpg';
    const fileName = `temuan_${Date.now()}_${Math.random().toString(36).substring(2, 7)}.${fileExt}`;

    const { data, error } = await supabase.storage
      .from('foto_temuan')
      .upload(fileName, bytes, {
        contentType: contentType || 'image/jpeg',
        upsert: true,
      });

    if (error) {
      console.warn('Supabase storage "foto_temuan" upload notice:', error.message);
      return dataUrl;
    }

    const { data: publicUrlData } = supabase.storage
      .from('foto_temuan')
      .getPublicUrl(data.path);

    if (publicUrlData && publicUrlData.publicUrl) {
      console.log('Generated Supabase Public CDN URL:', publicUrlData.publicUrl);
      return publicUrlData.publicUrl;
    }
  } catch (err) {
    console.warn('Supabase storage exception:', err);
  }

  return dataUrl;
}

/**
 * Syncs a single discovery record to Supabase table "public.kartu_temuan"
 * using required fields: image_url, nama_benda, real_shape, kelompok_id, is_proven
 */
export async function syncKartuTemuanToSupabase(discovery: {
  id?: number;
  photoUrl: string;
  objectName: string;
  realShape: string;
  groupId: number;
  isProven?: boolean;
  traitsVerified?: boolean;
}): Promise<void> {
  if (!isSupabaseConfigured) return;

  try {
    const payload: Record<string, any> = {
      image_url: discovery.photoUrl,
      nama_benda: discovery.objectName,
      real_shape: discovery.realShape,
      kelompok_id: discovery.groupId,
      is_proven: Boolean(discovery.isProven || discovery.traitsVerified),
    };

    if (discovery.id && discovery.id > 0) {
      payload.id = discovery.id;
    }

    const { error } = await supabase
      .from('kartu_temuan')
      .upsert(payload, { onConflict: 'id' });

    if (error) {
      console.warn('Supabase "kartu_temuan" upsert notice:', error.message);
      // Fallback insert without explicit id in case id is generated by sequence
      const { error: insertErr } = await supabase
        .from('kartu_temuan')
        .insert({
          image_url: discovery.photoUrl,
          nama_benda: discovery.objectName,
          real_shape: discovery.realShape,
          kelompok_id: discovery.groupId,
          is_proven: Boolean(discovery.isProven || discovery.traitsVerified),
        });
      if (insertErr) {
        console.warn('Supabase fallback insert notice:', insertErr.message);
      }
    }
  } catch (err) {
    console.warn('Supabase "kartu_temuan" sync exception:', err);
  }
}

/**
 * Fetches all records from Supabase table "public.kartu_temuan"
 */
export async function fetchKartuTemuanFromSupabase(): Promise<Array<{
  id: number;
  image_url: string;
  nama_benda: string;
  real_shape: string;
  kelompok_id: number;
  is_proven: boolean;
}>> {
  if (!isSupabaseConfigured) return [];

  try {
    const { data, error } = await supabase
      .from('kartu_temuan')
      .select('*')
      .order('id', { ascending: false });

    if (error) {
      console.warn('Supabase fetch "kartu_temuan" notice:', error.message);
      return [];
    }

    if (Array.isArray(data)) {
      return data.map((item: any, idx: number) => {
        const rawId = Number(item.id);
        const validId = !isNaN(rawId) && rawId !== 0 ? rawId : (idx + 1);
        const rawGroupId = Number(item.kelompok_id);
        const validGroupId = !isNaN(rawGroupId) && rawGroupId > 0 ? rawGroupId : 1;

        return {
          id: validId,
          image_url: String(item.image_url || ''),
          nama_benda: String(item.nama_benda || 'Benda Temuan'),
          real_shape: String(item.real_shape || 'lingkaran'),
          kelompok_id: validGroupId,
          is_proven: Boolean(item.is_proven),
        };
      });
    }
  } catch (err) {
    console.warn('Supabase fetch "kartu_temuan" exception:', err);
  }

  return [];
}

/**
 * Updates real_shape for a discovery in Supabase table "public.kartu_temuan"
 */
export async function updateDiscoveryShapeInSupabase(id: number, newRealShape: string): Promise<void> {
  if (!isSupabaseConfigured) return;
  try {
    const { error } = await supabase
      .from('kartu_temuan')
      .update({ real_shape: newRealShape })
      .eq('id', id);
    if (error) {
      console.warn('Supabase update shape notice:', error.message);
    }
  } catch (err) {
    console.warn('Supabase update shape exception:', err);
  }
}

/**
 * Resets all kartu_temuan records in Supabase (on session reset)
 */
export async function resetKartuTemuanInSupabase(): Promise<void> {
  if (!isSupabaseConfigured) return;
  try {
    const { error } = await supabase
      .from('kartu_temuan')
      .delete()
      .gte('id', 0);
    if (error) {
      console.warn('Supabase reset kartu_temuan notice:', error.message);
    }
  } catch (err) {
    console.warn('Supabase reset kartu_temuan exception:', err);
  }
}

export default supabase;
